{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "网关请求数据",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "somebody_somebody_request" }
   ]
  },
  {
   "title": "cpu使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[10m])) * 100"
    }
   ]
  },
  {
   "title": "驻留内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  }
 ]
}