global:
  scrape_interval:     60s
  evaluation_interval: 60s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "somebody"
    scrape_interval: 60s
    scrape_timeout: 60s
    metrics_path: "/metrics"

    static_configs:
      - targets: ["127.0.0.1:9091"] # if running in docker, place use ip
    honor_labels: true