[log]
log_level = "debug"

[http]
addr = "127.0.0.1"
port = 8080

[dnscache]
enable = false
type = "first" #first random noCache

[filepath]
original_path = ""
pid_file_location = "" #pid file path

[store]
store_type = "etcd"
store_host = "127.0.0.1"
store_port = 2379
store_namespace = "somebody"
store_user = ""
store_password = ""

[metric]
type = "prometheus"
addr = "127.0.0.1:9091"
namespace = "somebody"
instance = "somebody"
interval = 5