[log]
log_level  = "debug" #log level
log_format = "" #json
log_path   = "" #log/somebody.log

[httpConf]
addr   = "127.0.0.1:80"
addrHttps = ""

[filepath]
original_path = ""
pid_file_location = ""

[dnsCache]
strategy = "first"
expiration = 10
checkInterval = 5

[store]
registryAddr = "etcd://127.0.0.1:2379"
nameSpace    = "hordo"
userName     = ""
password     = ""

routerDegree = 3